version: '2'
services:
  embed:
    restart: always
    build:
      context: ./
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
      - "3001:${SERVER_PORT}"
    env_file:
      - .env
    volumes:
      - ${HOST_ASSET_ROOT}:${ASSET_ROOT}
      - /app/node_modules
      - ./server:/app/server
      - ./client:/app/client
    command: ['--host=0.0.0.0', '--port=${SERVER_PORT}', '--assetRoot=${ASSET_ROOT}', '--logLevel=debug']
  dataserver:
    restart: always
    image: index.docker.io/noterik/stageplayer-sbf-reader:latest
    volumes:
      - ${HOST_ASSET_ROOT}:/export
  measurementserver:
    restart: always
    image: index.docker.io/noterik/insync-measurement-reader:latest
    volumes:
      - ${HOST_ASSET_ROOT}:/data
    command: ['-d', '/data', '--logLevel', 'INFO']
  stageplayer:
    restart: always
    image: index.docker.io/noterik/marin-stageplayer:2.1.1-SNAPSHOT
