version: '2'
services:
  dataserver:
    restart: always
    image: index.docker.io/noterik/stageplayer-sbf-reader:latest
    volumes:
      - ${HOST_ASSET_ROOT}:/export
  measurementserver:
    restart: always
    image: index.docker.io/noterik/insync-measurement-reader:latest
    volumes:
      - ${HOST_ASSET_ROOT}:/data
    command: ['-d', '/data', '--logLevel', 'INFO']
  stageplayer:
    restart: always
    image: index.docker.io/noterik/marin-stageplayer:2.1.1-SNAPSHOT
    ports:
      - '2345:80'
  embed:
    restart: always
    build:
      context: ./
      dockerfile: dev.Dockerfile
    ports:
      - "${HOST_PORT}:8080"
    env_file:
      - .env
    volumes:
      - ${HOST_ASSET_ROOT}:/static
      - /app/node_modules
      - ./server:/app/server
      - ./client:/app/client
    command: [
      '--host=0.0.0.0',
      '--port=8080',
      '--assetRoot=/static',
      '--dataServer=http://measurementserver:8080',
      '--sbfDataServer=http://dataserver:8080',
      '--stageplayerServer=http://stageplayer',
      '--logLevel=debug'
    ]
