version: '2'
services:
  dataserver:
    restart: always
    image: index.docker.io/noterik/stageplayer-sbf-reader:latest
    volumes:
      - ${HOST_ASSET_ROOT}:${ASSET_ROOT}
  measurementserver:
    restart: always
    image: index.docker.io/noterik/insync-measurement-reader:latest
    volumes:
      - ${HOST_ASSET_ROOT}:/data/${ASSET_ROOT}
    command: ['-d', '/data', '--logLevel', 'INFO']
  proxy:
    image: nginx:alpine
    depends_on:
      - embed
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./example:/usr/share/nginx/html
    ports:
      - "${HOST_PORT}:80"
  stageplayer:
    image: index.docker.io/noterik/marin-stageplayer:2.4.0
    build:
      context: ../marin-stageplayer
  embed:
    restart: always
    build:
      context: ./
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - ${HOST_ASSET_ROOT}:${ASSET_ROOT}
      - /app/node_modules
      - ./server:/app/server
      - ./client:/app/client
      - ./constants.js:/app/constants.js
    command: [
      '--host=0.0.0.0',
      '--port=8080',
      '--assetRoot=${ASSET_ROOT}',
      '--dataServer=http://measurementserver:8080',
      '--sbfDataServer=http://dataserver:8080',
      '--libServer=http://stageplayer',
      '--logLevel=debug'
    ]
