version: '2'
services:
  dataserver:
    restart: always
    image: index.docker.io/noterik/stageplayer-sbf-reader:latest
    volumes:
      - ${HOST_ASSET_ROOT}:${ASSET_ROOT}
  measurementserver:
    restart: always
    image: index.docker.io/noterik/insync-measurement-reader:latest
    volumes:
      - ${HOST_ASSET_ROOT}:/data/${ASSET_ROOT}
    command: ['-d', '/data', '--logLevel', 'INFO']
  stageplayer:
    image: index.docker.io/noterik/marin-stageplayer:2.4.0
  embed:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ${HOST_ASSET_ROOT}:${ASSET_ROOT}
      - /app/node_modules
      - ./server:/app/server
      - ./constants.js:/app/constants.js
    command: [
      '--host=0.0.0.0',
      '--port=80',
      '--assetRoot=${ASSET_ROOT}',
      '--dataServer=http://measurementserver:8080',
      '--sbfDataServer=http://dataserver:8080',
      '--libServer=http://stageplayer',
      '--logLevel=debug'
    ]
