version: '2'
services:
  embed:
    restart: always
    build: 
      context: ./app
    env_file:
      - .env
    links:
      - dataserver
      - stageplayer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ${HOST_ASSET_ROOT}:/export
  dataserver:
    restart: always
    image: index.docker.io/noterik/stageplayer-sbf-reader:latest
    volumes:
      - ${HOST_ASSET_ROOT}:/export
  stageplayer:
    restart: always
    image: index.docker.io/noterik/marin-stageplayer:latest
