version: '2'
services:
  dataserver:
    restart: always
    image: index.docker.io/noterik/stageplayer-sbf-reader:latest
    volumes:
      - ${HOST_ASSET_ROOT}:${ASSET_ROOT}
  measurementserver:
    restart: always
    image: index.docker.io/noterik/insync-measurement-reader:1.2.0-beta.1
    volumes:
      - ${HOST_ASSET_ROOT}:/data/${ASSET_ROOT}
    ports:
      - 8081:8080
    command: ['-d', '/data', '--logLevel', 'INFO']
  stageplayer:
    image: index.docker.io/noterik/marin-stageplayer:3.1.0-beta.1
    ports:
      - 80:80
